import { useState } from "react";
import type { EngineeringValue,OutletResult,SimulationResult } from "../../api/contracts";
import { unavailableReason,useI18n } from "../../i18n/i18n";
import { formatValue } from "./format";
export type Metric="airflow_percentage"|"airflow_cfm"|"airflow_cmh"|"outlet_velocity_mps";

function Cell({outlet,metric,selected,onSelect,range}:{outlet:OutletResult;metric:Metric;selected:boolean;onSelect:()=>void;range:[number,number]}){const {t}=useI18n();const value=outlet[metric] as EngineeringValue;const missing=value.availability==="unavailable"||value.value===null;const intensity=missing||range[1]===range[0]?0.5:(value.value!-range[0])/(range[1]-range[0]);return <button type="button" className={`result-cell ${selected?"selected":""} ${missing?"unavailable":""}`} style={missing?undefined:{"--heat":intensity} as React.CSSProperties} onClick={onSelect} aria-label={t("selectOutlet",{id:outlet.outlet_id})}><strong>{outlet.outlet_id}</strong><span>{formatValue(value)}</span><small>{formatValue(outlet.airflow_percentage)} · {formatValue(outlet.airflow_cfm)}</small><small>{formatValue(outlet.airflow_cmh)}</small><small>{missing?t("velocityUnavailable"):formatValue(outlet.outlet_velocity_mps)}</small></button>}
function Detail({outlet}:{outlet:OutletResult}){const {t}=useI18n();const missing=outlet.outlet_velocity_mps.availability==="unavailable";return <section className="detail-card" aria-label={t("selectedOutlet")}><div className="detail-title"><span>{t("selectedOutlet")}</span><strong>{outlet.outlet_id}</strong></div><dl className="detail-grid"><div><dt>{t("airflow")}</dt><dd>{formatValue(outlet.airflow_percentage)}</dd></div><div><dt>{t("flow")}</dt><dd>{formatValue(outlet.airflow_cfm)}</dd></div><div><dt>{t("convertedFlow")}</dt><dd>{formatValue(outlet.airflow_cmh)}</dd></div><div><dt>{t("velocity")}</dt><dd>{missing?t("velocityUnavailable"):formatValue(outlet.outlet_velocity_mps)}</dd></div><div><dt>{t("geometricArea")}</dt><dd>{formatValue(outlet.geometric_area_m2,6)}</dd></div><div><dt>{t("freeAreaRatio")}</dt><dd>{formatValue(outlet.free_area_ratio)}</dd></div><div><dt>{t("effectiveArea")}</dt><dd>{formatValue(outlet.effective_area_m2,6)}</dd></div><div><dt>{t("reasonCode")}</dt><dd><code>{outlet.outlet_velocity_mps.unavailable_reason??"—"}</code></dd></div></dl>{missing&&<p className="reason-explanation">{unavailableReason(outlet.outlet_velocity_mps.unavailable_reason,t)}</p>}<details><summary>{t("calculationProvenance")}</summary><pre>{JSON.stringify(outlet.calculation_provenance,null,2)}</pre></details></section>}

export function ResultPanel({result}:{result:SimulationResult|null}){const {t}=useI18n();const [metric,setMetric]=useState<Metric>("airflow_percentage");const [selectedId,setSelectedId]=useState<string|null>(null);if(!result)return <aside className="panel results-panel empty-results"><span className="status-dot idle"/><h2>{t("ready")}</h2><p>{t("readyDescription")}</p></aside>;const selected=result.outlets.find(item=>item.outlet_id===selectedId)??result.outlets[0];const available=result.outlets.map(item=>(item[metric] as EngineeringValue).value).filter((value):value is number=>value!==null);const range:[number,number]=available.length?[Math.min(...available),Math.max(...available)]:[0,0];const metrics:{key:Metric;label:string}[]=[{key:"airflow_percentage",label:t("airflowPercent")},{key:"airflow_cfm",label:"CFM"},{key:"airflow_cmh",label:"m³/h"},{key:"outlet_velocity_mps",label:"m/s"}];return <aside className="panel results-panel" aria-labelledby="results-title"><div className="result-status"><div><span className="status-dot complete"/>{t("completed")}</div><span>{t("conservation")} {result.conserved?t("pass"):t("fail")}</span></div><div className="section-heading"><span className="eyebrow">{result.solver}</span><h2 id="results-title">{t("simulationResults")}</h2></div><div className="summary-grid"><div><span>{t("inletSummary")}</span><b>{formatValue(result.total_inlet_airflow_cfm)}</b><small>{formatValue(result.total_inlet_airflow_cmh)}</small></div><div><span>{t("outletsSummary")}</span><b>{formatValue(result.total_outlet_airflow_cfm)}</b><small>{formatValue(result.total_outlet_airflow_cmh)}</small></div><div><span>{t("uniformity")}</span><b>{formatValue(result.uniformity_index)}</b><small>{t("minMax")}</small></div><div><span>{t("error")}</span><b>{formatValue(result.conservation_error_cfm,6)}</b><small>{result.outlet_count} {t("outlets")} · {result.deflector_count} {t("deflectors")}</small></div></div><div className="metric-row"><label htmlFor="heat-metric">{t("heatMetric")}</label><select id="heat-metric" value={metric} onChange={event=>setMetric(event.target.value as Metric)}>{metrics.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></div><div className="legend"><span>{t("low")}</span><div/><span>{t("high")}</span><i>{t("valuesVisible")}</i></div><div className="result-grid" style={{gridTemplateColumns:`repeat(${result.columns},minmax(0,1fr))`}}>{result.outlets.map(outlet=><Cell key={outlet.outlet_id} outlet={outlet} metric={metric} selected={selected.outlet_id===outlet.outlet_id} onSelect={()=>setSelectedId(outlet.outlet_id)} range={range}/>)}</div><Detail outlet={selected}/><div className="model-notice"><strong>{t("experimentalTitle")}</strong><p>{t("experimentalNotice")}</p></div></aside>}
