import { useState,type Dispatch,type SetStateAction } from "react";
import type { SimulationResult } from "../../api/contracts";
import { runSimulation,SimulationApiError } from "../../api/simulation";
import { useI18n,type TranslationKey } from "../../i18n/i18n";
import { GeometryPreview } from "./GeometryPreview";
import { INITIAL_FORM,toSimulationRequest,type WorkspaceForm } from "./initialState";
import { InputPanel,type WorkspaceError } from "./InputPanel";
import { ResultPanel } from "./ResultPanel";

function validate(form:WorkspaceForm,t:(key:TranslationKey,values?:Record<string,string|number>)=>string):WorkspaceError[]{const errors:WorkspaceError[]=[];const positive:[TranslationKey,number][]=[["grilleWidth",form.grille_width_mm],["grilleHeight",form.grille_height_mm],["plenumDepth",form.plenum_depth_mm],["inletWidth",form.inlet_width_mm],["inletHeight",form.inlet_height_mm],["outletWidth",form.outlet_width_mm],["outletHeight",form.outlet_height_mm]];positive.forEach(([key,value])=>{if(!Number.isFinite(value)||value<=0)errors.push({message:t("positiveError",{field:t(key)})})});if(form.fans.some(fan=>!Number.isFinite(fan.frequency_hz)||fan.frequency_hz<0||fan.frequency_hz>60))errors.push({message:t("fanFrequencyError")});if(!form.fans.some(fan=>fan.enabled&&fan.frequency_hz>0))errors.push({message:t("fanRequiredError")});const inletValues=[...Object.values(form.inlet.position),...Object.values(form.inlet.direction)];if(inletValues.some(value=>!Number.isFinite(value)))errors.push({message:t("inletVectorFiniteError")});else if(Math.hypot(form.inlet.direction.x,form.inlet.direction.y,form.inlet.direction.z)===0)errors.push({message:t("inletDirectionZeroError")});if(!Number.isInteger(form.rows)||form.rows<=0||!Number.isInteger(form.columns)||form.columns<=0)errors.push({message:t("gridIntegerError")});else if(form.rows*form.columns!==8)errors.push({message:t("eightOutletsError")});if(form.free_area_percent.trim()!==""){const ratio=Number(form.free_area_percent);if(!Number.isFinite(ratio)||ratio<=0||ratio>100)errors.push({message:t("freeAreaError")})}form.deflectors.forEach((item,index)=>{if(!item.identifier.trim())errors.push({message:t("deflectorIdError",{index:index+1})});if(item.width_m<=0||item.height_m<=0)errors.push({message:t("deflectorDimensionError",{index:index+1})})});return errors}

export function SimulationWorkspace(){const {language,setLanguage,t}=useI18n();const [form,setForm]=useState<WorkspaceForm>(()=>structuredClone(INITIAL_FORM));const [result,setResult]=useState<SimulationResult|null>(null);const [errors,setErrors]=useState<WorkspaceError[]>([]);const [running,setRunning]=useState(false);const setFormAndInvalidate:Dispatch<SetStateAction<WorkspaceForm>>=update=>{setForm(current=>typeof update==="function"?update(current):update);setResult(null)};const submit=async()=>{const validation=validate(form,t);if(validation.length){setErrors(validation);return}setRunning(true);setErrors([]);try{setResult(await runSimulation(toSimulationRequest(form)))}catch(error){const apiError=error instanceof SimulationApiError;setErrors([{message:apiError?(error.status===0?t("apiUnavailable"):t("apiError")):t("apiUnavailable"),technical:apiError?`HTTP ${error.status}: ${error.technicalDetail}`:error instanceof Error?error.message:String(error)}])}finally{setRunning(false)}};const reset=()=>{setForm(structuredClone(INITIAL_FORM));setResult(null);setErrors([])};return <main>
  <header className="app-header"><div className="brand"><span>ADD</span><div><strong>{t("appName")}</strong><small>{t("workspaceVersion")}</small></div></div><div className="header-tools"><label>{t("language")}<select aria-label={t("language")} value={language} onChange={event=>setLanguage(event.target.value as "zh-TW"|"en")}><option value="zh-TW">繁體中文</option><option value="en">English</option></select></label><div className="header-state"><span className="status-dot idle"/>{t("localSession")} <b>{t("unsaved")}</b></div></div></header>
  <div className="workspace-title"><div><span className="eyebrow">{t("workspaceKicker")}</span><h1>{t("workspaceTitle")}</h1></div><p>{t("workspaceIntro")}</p></div>
  <div className="workspace-grid"><InputPanel form={form} result={result} setForm={setFormAndInvalidate} running={running} errors={errors} onRun={submit} onReset={reset}/><div className="center-column"><GeometryPreview form={form} result={result}/><div className="boundary-note"><b>{t("modelBoundary")}</b><span>{t("modelBoundaryText")}</span></div></div><ResultPanel result={result}/></div>
  </main>}
