import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { I18nProvider } from "../../i18n/i18n";
import { SimulationWorkspace } from "./SimulationWorkspace";

vi.mock("./EngineeringScene3D",()=>({EngineeringScene3D:({cameraView,showParticles}:{cameraView:string;showParticles:boolean})=><div role="img" aria-label="mock engineering scene" data-testid="engineering-3d-scene" data-camera={cameraView} data-particles={showParticles}/> }));

const value=(number:number|null,unit:string,reason:string|null=null)=>({availability:number===null?"unavailable":"available",value:number,unit,unavailable_reason:reason,provenance:number===null?null:{source_type:"solver",source_reference:"test",solver_component:"test",model_relationship:"test"}});
const fanResults=[{equipment_id:"SF-501",enabled:true,status:"RUNNING",frequency_hz:value(50,"Hz"),motor_power_hp:value(100,"HP"),rated_airflow_cmh:value(110000,"m^3/h"),rated_static_pressure_pa:value(1600,"Pa"),maximum_frequency_hz:value(60,"Hz"),current_airflow_cmh:value(91666.6667,"m^3/h"),current_airflow_cfm:value(53953.64,"CFM"),current_static_pressure_pa:value(1111.111,"Pa"),inlet_velocity_mps:value(159.1435,"m/s"),estimation_label:"Estimated using Fan Affinity Laws"},{equipment_id:"SF-502",enabled:false,status:"OFF",frequency_hz:value(0,"Hz"),motor_power_hp:value(100,"HP"),rated_airflow_cmh:value(110000,"m^3/h"),rated_static_pressure_pa:value(1600,"Pa"),maximum_frequency_hz:value(60,"Hz"),current_airflow_cmh:value(0,"m^3/h"),current_airflow_cfm:value(0,"CFM"),current_static_pressure_pa:value(0,"Pa"),inlet_velocity_mps:value(0,"m/s"),estimation_label:"Estimated using Fan Affinity Laws"}] as const;
const result={status:"completed",solver:"Experimental Airflow Solver V0.1",claim_label:"experimental_scaled_distribution",experimental_notice:"backend notice",rows:2,columns:4,outlet_count:8,deflector_count:1,fan_operating_results:fanResults,total_inlet_airflow_cfm:value(800,"CFM"),total_inlet_airflow_cmh:value(1359.208656,"m^3/h"),total_outlet_airflow_cfm:value(800,"CFM"),total_outlet_airflow_cmh:value(1359.208656,"m^3/h"),conservation_error_cfm:value(0,"CFM"),conserved:true,uniformity_index:value(.571,"ratio"),outlets:Array.from({length:8},(_,i)=>({outlet_id:`R${Math.floor(i/4)}C${i%4}`,row:Math.floor(i/4),column:i%4,airflow_percentage:value(i===3?17.942:9.083,"%"),airflow_cfm:value(i===3?143.535:72.664,"CFM"),airflow_cmh:value(i===3?243.867:123.457,"m^3/h"),outlet_velocity_mps:i===0?value(null,"m/s","OUTLET_VELOCITY_FREE_AREA_RATIO_UNAVAILABLE"):value(1.613,"m/s"),geometric_area_m2:value(.09,"m^2"),free_area_ratio:value(.7,"ratio"),effective_area_m2:value(.063,"m^2"),calculation_provenance:{airflow_m3s:value(.0677,"m^3/s")}})),diagnostics:[],assumptions:[]};
const renderWorkspace=()=>render(<I18nProvider><SimulationWorkspace/></I18nProvider>);

describe("Simulation workspace review fix",()=>{
  beforeEach(()=>{localStorage.clear();vi.stubGlobal("fetch",vi.fn(async()=>({ok:true,json:async()=>result})))});

  it("defaults to Traditional Chinese and persists English selection",async()=>{renderWorkspace();expect(screen.getByRole("heading",{name:"氣流模擬工作區"})).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText("語言"),"en");expect(screen.getByRole("heading",{name:"Airflow Simulation Workspace"})).toBeInTheDocument();expect(localStorage.getItem("add.language")).toBe("en")});

  it("submits canonical free-area and fan controls without UI-only fields",async()=>{renderWorkspace();await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));await waitFor(()=>expect(fetch).toHaveBeenCalled());const body=JSON.parse((fetch as ReturnType<typeof vi.fn>).mock.calls[0][1].body);expect(body.free_area_ratio).toBe(.7);expect(body).not.toHaveProperty("free_area_percent");expect(body).not.toHaveProperty("total_airflow_cfm");expect(body.fans).toEqual([{equipment_id:"SF-501",enabled:true,frequency_hz:50},{equipment_id:"SF-502",enabled:false,frequency_hz:0}])});

  it("controls both real fans independently and displays backend fan estimates",async()=>{renderWorkspace();await userEvent.selectOptions(screen.getByLabelText("SF-502 運轉預設"),"60");await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));await waitFor(()=>expect(fetch).toHaveBeenCalled());const body=JSON.parse((fetch as ReturnType<typeof vi.fn>).mock.calls[0][1].body);expect(body.fans[1]).toEqual({equipment_id:"SF-502",enabled:true,frequency_hz:60});expect(await screen.findAllByText("依風機相似定律估算")).toHaveLength(2);expect(screen.getByText("91666.667 m^3/h")).toBeInTheDocument()});

  it("rejects fan frequency above the verified 60 Hz maximum",async()=>{renderWorkspace();await userEvent.selectOptions(screen.getByLabelText("SF-501 運轉預設"),"custom");fireEvent.change(screen.getByLabelText("SF-501 頻率 Hz"),{target:{value:"61"}});await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));expect(screen.getByRole("alert")).toHaveTextContent("風機頻率必須介於 0 至 60 Hz")});

  it("maps all inlet presets to the canonical solver direction",async()=>{renderWorkspace();const preset=screen.getByLabelText("方向預設");const cases=[...([ ["downward",[0,0,-1]],["upward",[0,0,1]],["leftToRight",[1,0,0]],["rightToLeft",[-1,0,0]],["frontToBack",[0,1,0]],["backToFront",[0,-1,0]] ] as const)];for(const [name,expected] of cases){await userEvent.selectOptions(preset,name);await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));await waitFor(()=>expect(fetch).toHaveBeenCalledTimes(cases.indexOf(cases.find(item=>item[0]===name)!)+1));const body=JSON.parse((fetch as ReturnType<typeof vi.fn>).mock.calls.at(-1)![1].body);expect(Object.values(body.inlet.direction)).toEqual(expected)}});

  it("normalizes a custom diagonal, forwards position, and rejects zero direction",async()=>{renderWorkspace();await userEvent.selectOptions(screen.getByLabelText("方向預設"),"custom");fireEvent.change(screen.getByLabelText("入口位置 X"),{target:{value:"0.25"}});fireEvent.change(screen.getByLabelText("入口方向 X"),{target:{value:"1"}});fireEvent.change(screen.getByLabelText("入口方向 Y"),{target:{value:"2"}});fireEvent.change(screen.getByLabelText("入口方向 Z"),{target:{value:"-2"}});await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));await waitFor(()=>expect(fetch).toHaveBeenCalled());const body=JSON.parse((fetch as ReturnType<typeof vi.fn>).mock.calls[0][1].body);expect(body.inlet.position.x).toBe(.25);expect(body.inlet.direction).toEqual({x:1/3,y:2/3,z:-2/3});fireEvent.change(screen.getByLabelText("入口方向 X"),{target:{value:"0"}});fireEvent.change(screen.getByLabelText("入口方向 Y"),{target:{value:"0"}});fireEvent.change(screen.getByLabelText("入口方向 Z"),{target:{value:"0"}});await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));expect(screen.getByRole("alert")).toHaveTextContent("入口方向不可為零長度向量")});

  it("marks solver results stale after inlet geometry changes",async()=>{renderWorkspace();await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));expect(await screen.findByRole("heading",{name:"模擬結果"})).toBeInTheDocument();fireEvent.change(screen.getByLabelText("入口位置 X"),{target:{value:"0.2"}});expect(screen.getByRole("heading",{name:"等待執行模擬"})).toBeInTheDocument();expect(screen.getByLabelText("3D 熱圖指標")).toBeDisabled()});

  it("supports zero deflectors and preserves missing free area",async()=>{renderWorkspace();await userEvent.click(screen.getByRole("button",{name:"移除"}));fireEvent.change(screen.getByLabelText("有效開口率 %"),{target:{value:""}});await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));await waitFor(()=>expect(fetch).toHaveBeenCalled());const body=JSON.parse((fetch as ReturnType<typeof vi.fn>).mock.calls[0][1].body);expect(body.deflectors).toEqual([]);expect(body.free_area_ratio).toBeNull()});

  it("provides the engineering 3D scene and all quick camera views",async()=>{renderWorkspace();expect(screen.getByTestId("engineering-3d-scene")).toHaveAttribute("data-camera","isometric");const side=screen.getByRole("button",{name:"側視圖"});await userEvent.click(side);expect(side).toHaveAttribute("aria-pressed","true");expect(screen.getByTestId("engineering-3d-scene")).toHaveAttribute("data-camera","side");expect(screen.getByLabelText("3D 熱圖指標")).toBeDisabled()});

  it("localizes validation messages in zh-TW and English",async()=>{const view=renderWorkspace();await userEvent.click(screen.getByLabelText("SF-501 啟用"));await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));expect(screen.getByRole("alert")).toHaveTextContent("至少一台已啟用風機必須以高於 0 Hz 運轉");view.unmount();localStorage.setItem("add.language","en");renderWorkspace();await userEvent.click(screen.getByLabelText("SF-501 Enabled"));await userEvent.click(screen.getByRole("button",{name:"Run simulation"}));expect(screen.getByRole("alert")).toHaveTextContent("At least one enabled fan must operate above 0 Hz")});

  it("shows readable API errors with expandable diagnostics in both languages",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>({ok:false,status:422,statusText:"Invalid",json:async()=>({detail:[{type:"extra_forbidden",loc:["body","bad"],msg:"technical"}]})})));const view=renderWorkspace();await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));expect(await screen.findByRole("alert")).toHaveTextContent("模擬無法完成，請檢查輸入後再試一次");expect(screen.getByText("技術診斷資訊")).toBeInTheDocument();view.unmount();localStorage.setItem("add.language","en");renderWorkspace();await userEvent.click(screen.getByRole("button",{name:"Run simulation"}));expect(await screen.findByRole("alert")).toHaveTextContent("The simulation could not be completed");expect(screen.getByText("Technical diagnostics")).toBeInTheDocument()});

  it("renders localized result summary, heat map, detail, provenance, and unavailable reason",async()=>{renderWorkspace();await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));expect(await screen.findByRole("heading",{name:"模擬結果"})).toBeInTheDocument();expect(screen.getByLabelText("熱圖指標",{selector:"#heat-metric"})).toBeInTheDocument();expect(screen.getAllByText("17.942 %").length).toBeGreaterThan(0);expect(screen.getAllByText("出口速度不可用").length).toBeGreaterThan(0);expect(screen.getByText("未提供有效開口率，因此無法計算出口速度。")).toBeInTheDocument();expect(screen.getByText("計算來源追溯")).toBeInTheDocument();expect(screen.getByText("實驗模型 · 非 CFD")).toBeInTheDocument()});

  it("changes heat metric, disables during loading, and resets",async()=>{let resolve!:(value:unknown)=>void;vi.stubGlobal("fetch",vi.fn(()=>new Promise(r=>{resolve=r})));renderWorkspace();const inletWidth=screen.getByLabelText("入口寬度 mm");fireEvent.change(inletWidth,{target:{value:"500"}});await userEvent.click(screen.getByRole("button",{name:"執行模擬"}));expect(screen.getByRole("button",{name:"求解中…"})).toBeDisabled();resolve({ok:true,json:async()=>result});const selector=await screen.findByLabelText("熱圖指標",{selector:"#heat-metric"});await userEvent.selectOptions(selector,"airflow_cmh");expect(selector).toHaveValue("airflow_cmh");await userEvent.click(screen.getByRole("button",{name:"重設"}));expect(inletWidth).toHaveValue(400)});
});

