import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Language = "zh-TW" | "en";

const en = {
  appName:"Air Deflector Designer", workspaceVersion:"ENGINEERING WORKSPACE · V0.1", localSession:"LOCAL SESSION", unsaved:"UNSAVED",
  workspaceKicker:"AIRFLOW DISTRIBUTION / EXPERIMENTAL", workspaceTitle:"Airflow Simulation Workspace", workspaceIntro:"Configure the eight-cell outlet, inspect the live 3D geometry, and deliberately run the backend solver.",
  language:"Language", designParameters:"Design parameters", simulationInput:"SIMULATION INPUT", inletSection:"01 · Inlet airflow", grilleSection:"03 · Grille geometry", outletSection:"04 · Outlet grid", deflectorSection:"05 · Deflectors",
  totalAirflow:"Total airflow", inletWidth:"Inlet width", inletHeight:"Inlet height", direction:"Direction", solverCoordinates:"solver coordinates", grilleWidth:"Grille width", grilleHeight:"Grille height", plenumDepth:"Plenum depth", rows:"Rows", columns:"Columns", outletWidth:"Outlet width", outletHeight:"Outlet height", freeArea:"Free area", count:"count",
  inletBoundary:"Inlet airflow boundary", directionPreset:"Direction preset", inletPosition:"Inlet position", inletDirection:"Inlet direction", normalizedOnRun:"normalized for solver and visualization", presetDownward:"Downward (−Z)", presetUpward:"Upward (+Z)", presetLeftToRight:"Left to right (+X)", presetRightToLeft:"Right to left (−X)", presetFrontToBack:"Front to back (+Y)", presetBackToFront:"Back to front (−Y)", presetCustom:"Custom vector", coordinateConvention:"Global solver coordinates: X = left/right, Y = front/back across the outlet plane, Z = vertical/plenum depth. The 3D adapter maps these axes explicitly without changing solver values.",
  fanSection:"02 · Site supply fans", enabled:"Enabled", disabled:"Disabled", fanPreset:"Operating preset", fanCustom:"Custom", frequency:"Frequency", currentStatus:"Current status", currentAirflow:"Current airflow", currentPressure:"Current static pressure", awaitingSolver:"Awaiting solver", affinityEstimate:"Estimated using Fan Affinity Laws", runForFanEstimate:"Run simulation to calculate fan operating values", fanStatusOFF:"OFF", fanStatusSTANDBY:"STANDBY", fanStatusRUNNING:"RUNNING",
  gridNote:"V0.1 supports exactly eight outlets. Blank free area keeps velocity unavailable.", width:"Width", height:"Height", angle:"Angle", positionX:"Position X", positionY:"Position Y", positionZ:"Position Z", remove:"Remove", addDeflector:"+ Add deflector", reset:"Reset", runSimulation:"Run simulation", runningSolver:"Running solver…",
  checkInputs:"Check simulation inputs", positiveError:"{field} must be greater than zero.", gridIntegerError:"Rows and columns must be positive integers.", eightOutletsError:"Experimental Airflow Solver V0.1 requires exactly eight outlets.", freeAreaError:"Free area must be greater than 0% and no more than 100%.", deflectorIdError:"Deflector {index} requires an identifier.", deflectorDimensionError:"Deflector {index} dimensions must be greater than zero.", apiError:"The simulation could not be completed. Check the inputs and try again.", apiUnavailable:"The simulation service is unavailable. Confirm that the API is running and try again.", technicalDiagnostics:"Technical diagnostics",
  inletDirectionZeroError:"Inlet direction must not be a zero-length vector.", inletVectorFiniteError:"Inlet position and direction must contain finite numbers.",
  fanFrequencyError:"Fan frequency must be between 0 and 60 Hz.", fanRequiredError:"At least one enabled fan must operate above 0 Hz.",
  geometryPreview:"Geometry preview", outletFaceView:"Outlet Face View", sideSectionView:"Side Section View", outletFaceKicker:"FRONT VIEW / LOOKING ALONG −Z", sideSectionKicker:"SIDE SECTION / LOOKING ALONG −Y", outletFaceDescription:"Grille plane, outlet IDs, solver-result heat overlay, and valid deflector projection only.", sideDescription:"X–Z section showing inlet direction, plenum depth, grille plane, and deflector angle about +Y.", outletGrid:"Outlet grid", deflectorProjection:"Deflector projection", heatOverlay:"Airflow % overlay", unavailable:"Unavailable", grillePlane:"GRILLE PLANE", inlet:"INLET", plenum:"PLENUM", depth:"DEPTH", viewingDirection:"VIEW −Y", axisX:"X", axisY:"Y", axisZ:"Z", deflector:"DEFLECTOR", noFlowField:"Schematic only · no CFD or streamlines", modelBoundary:"Model boundary", modelBoundaryText:"Interactive 3D geometry · solver-output overlays only · no pressure, turbulence, or CFD field",
  engineering3dKicker:"TRUE 3D GEOMETRY / SOLVER-DRIVEN OVERLAYS", engineering3dTitle:"Engineering 3D Visualization", notCfdBadge:"ENGINEERING VIEW · NOT CFD", viewControls:"3D visualization controls", quickViews:"Quick camera views", cameraIsometric:"Isometric", cameraFront:"Front", cameraSide:"Side", cameraTop:"Top", sceneHeatMetric:"3D heat-map metric", annotations:"Annotations", flowIndicators:"Flow indicators", cameraHelp:"Rotate · pan · zoom with pointer controls", solverVisualActive:"Heat map and indicators are derived from the latest solver result", geometryOnly:"Geometry-only preview · editing does not run the solver", engineeringSceneDescription:"Interactive three-dimensional engineering view of the inlet, plenum, outlet grid, and deflectors. It is not a CFD flow field.",
  ready:"Ready to simulate", readyDescription:"Review the interactive 3D geometry, then run the solver. Results are not generated while editing.", completed:"COMPLETED", conservation:"Conservation", pass:"PASS", fail:"FAIL", simulationResults:"Simulation results", inletSummary:"Inlet", outletsSummary:"Outlets", uniformity:"Uniformity", error:"Error", minMax:"min / max", outlets:"outlets", deflectors:"deflectors",
  heatMetric:"Heat-map metric", airflowPercent:"Airflow %", low:"LOW", high:"HIGH", valuesVisible:"Numerical values remain visible in every cell", selectOutlet:"Select {id}", velocityUnavailable:"Velocity unavailable", selectedOutlet:"SELECTED OUTLET", airflow:"Airflow", flow:"Flow", convertedFlow:"Converted flow", velocity:"Velocity", geometricArea:"Geometric area", freeAreaRatio:"Free-area ratio", effectiveArea:"Effective area", reasonCode:"Reason code", calculationProvenance:"Calculation provenance",
  experimentalTitle:"Experimental model · Not CFD", experimentalNotice:"This is an experimental distribution model, not CFD. It does not model pressure, turbulence, resistance, or full fluid dynamics.",
  reasonFreeAreaUnavailable:"Velocity is unavailable because no free-area ratio was supplied.", reasonFreeAreaInvalid:"Velocity is unavailable because the free-area ratio is invalid.", reasonWidthUnavailable:"Velocity is unavailable because outlet width is missing.", reasonWidthInvalid:"Velocity is unavailable because outlet width is invalid.", reasonHeightUnavailable:"Velocity is unavailable because outlet height is missing.", reasonHeightInvalid:"Velocity is unavailable because outlet height is invalid.", reasonUnknown:"Velocity is unavailable. See the technical reason code.",
};

export type TranslationKey = keyof typeof en;
const zh: Record<TranslationKey,string> = {
  appName:"導風板設計工具", workspaceVersion:"工程工作區 · V0.1", localSession:"本機工作階段", unsaved:"尚未儲存",
  workspaceKicker:"氣流分配／實驗模型", workspaceTitle:"氣流模擬工作區", workspaceIntro:"設定八格出風口、即時檢查 3D 幾何，再明確執行後端求解器。",
  language:"語言", designParameters:"設計參數", simulationInput:"模擬輸入", inletSection:"01 · 入口氣流", grilleSection:"03 · 格柵幾何", outletSection:"04 · 出風口陣列", deflectorSection:"05 · 導風板",
  totalAirflow:"總入口風量", inletWidth:"入口寬度", inletHeight:"入口高度", direction:"方向", solverCoordinates:"求解器座標", grilleWidth:"格柵寬度", grilleHeight:"格柵高度", plenumDepth:"靜壓箱深度", rows:"列數", columns:"欄數", outletWidth:"單格寬度", outletHeight:"單格高度", freeArea:"有效開口率", count:"數量",
  inletBoundary:"入口氣流邊界條件", directionPreset:"方向預設", inletPosition:"入口位置", inletDirection:"入口方向", normalizedOnRun:"供求解器與視覺化使用前正規化", presetDownward:"向下（−Z）", presetUpward:"向上（+Z）", presetLeftToRight:"由左至右（+X）", presetRightToLeft:"由右至左（−X）", presetFrontToBack:"由前至後（+Y）", presetBackToFront:"由後至前（−Y）", presetCustom:"自訂向量", coordinateConvention:"全域求解器座標：X＝左右、Y＝出風口平面前後、Z＝垂直／靜壓箱深度。3D 轉接層會明確映射軸向，不改變求解器數值。",
  fanSection:"02 · 現場送風機", enabled:"啟用", disabled:"停用", fanPreset:"運轉預設", fanCustom:"自訂", frequency:"頻率", currentStatus:"目前狀態", currentAirflow:"目前風量", currentPressure:"目前靜壓", awaitingSolver:"等待求解", affinityEstimate:"依風機相似定律估算", runForFanEstimate:"執行模擬後計算風機運轉值", fanStatusOFF:"停止", fanStatusSTANDBY:"待機", fanStatusRUNNING:"運轉中",
  gridNote:"V0.1 僅支援八個出風口。有效開口率留白時，出口速度會保持不可用。", width:"寬度", height:"高度", angle:"角度", positionX:"X 位置", positionY:"Y 位置", positionZ:"Z 位置", remove:"移除", addDeflector:"＋ 新增導風板", reset:"重設", runSimulation:"執行模擬", runningSolver:"求解中…",
  checkInputs:"請檢查模擬輸入", positiveError:"{field}必須大於零。", gridIntegerError:"列數與欄數必須是正整數。", eightOutletsError:"實驗氣流求解器 V0.1 必須使用八個出風口。", freeAreaError:"有效開口率必須大於 0%，且不得超過 100%。", deflectorIdError:"導風板 {index} 必須有識別碼。", deflectorDimensionError:"導風板 {index} 的尺寸必須大於零。", apiError:"模擬無法完成，請檢查輸入後再試一次。", apiUnavailable:"無法連線至模擬服務，請確認 API 已啟動後再試一次。", technicalDiagnostics:"技術診斷資訊",
  inletDirectionZeroError:"入口方向不可為零長度向量。", inletVectorFiniteError:"入口位置與方向必須是有限數值。",
  fanFrequencyError:"風機頻率必須介於 0 至 60 Hz。", fanRequiredError:"至少一台已啟用風機必須以高於 0 Hz 運轉。",
  geometryPreview:"幾何預覽", outletFaceView:"出風口正視圖", sideSectionView:"側剖面圖", outletFaceKicker:"正視圖／沿 −Z 方向觀看", sideSectionKicker:"側剖面／沿 −Y 方向觀看", outletFaceDescription:"僅顯示格柵平面、出風口編號、求解結果熱圖與此平面有效的導風板投影。", sideDescription:"X–Z 剖面顯示入口方向、靜壓箱深度、格柵平面，以及繞 +Y 軸的導風板角度。", outletGrid:"出風口陣列", deflectorProjection:"導風板投影", heatOverlay:"風量百分比熱圖", unavailable:"不可用", grillePlane:"格柵平面", inlet:"入口", plenum:"靜壓箱", depth:"深度", viewingDirection:"視線 −Y", axisX:"X", axisY:"Y", axisZ:"Z", deflector:"導風板", noFlowField:"僅為幾何示意 · 非 CFD、無流線", modelBoundary:"模型邊界", modelBoundaryText:"互動式 3D 幾何 · 僅顯示求解器輸出圖層 · 不包含壓力、紊流或 CFD 場",
  engineering3dKicker:"真實 3D 幾何／求解器驅動圖層", engineering3dTitle:"工程 3D 視覺化", notCfdBadge:"工程視圖 · 非 CFD", viewControls:"3D 視覺化控制", quickViews:"快速相機視角", cameraIsometric:"等角視圖", cameraFront:"正視圖", cameraSide:"側視圖", cameraTop:"俯視圖", sceneHeatMetric:"3D 熱圖指標", annotations:"工程標註", flowIndicators:"氣流指示粒子", cameraHelp:"使用指標裝置旋轉、平移與縮放", solverVisualActive:"熱圖與指示粒子均取自最近一次求解器結果", geometryOnly:"僅預覽幾何 · 編輯不會執行求解器", engineeringSceneDescription:"入口、靜壓箱、出風口陣列與導風板的互動式三維工程視圖；此視圖不是 CFD 流場。",
  ready:"等待執行模擬", readyDescription:"請先檢查互動式 3D 幾何，再執行求解器。編輯過程不會自動產生結果。", completed:"已完成", conservation:"守恆檢查", pass:"通過", fail:"失敗", simulationResults:"模擬結果", inletSummary:"入口", outletsSummary:"出風口合計", uniformity:"均勻度指標", error:"守恆誤差", minMax:"最小值／最大值", outlets:"個出風口", deflectors:"片導風板",
  heatMetric:"熱圖指標", airflowPercent:"風量 %", low:"低", high:"高", valuesVisible:"每一格均保留數值，不只依賴顏色", selectOutlet:"選取 {id}", velocityUnavailable:"出口速度不可用", selectedOutlet:"已選取出風口", airflow:"風量比例", flow:"風量", convertedFlow:"換算風量", velocity:"出口速度", geometricArea:"幾何面積", freeAreaRatio:"有效開口率", effectiveArea:"有效面積", reasonCode:"原因代碼", calculationProvenance:"計算來源追溯",
  experimentalTitle:"實驗模型 · 非 CFD", experimentalNotice:"這是實驗性的氣流分配模型，不是 CFD；不模擬壓力、紊流、阻力或完整流體動力學。",
  reasonFreeAreaUnavailable:"未提供有效開口率，因此無法計算出口速度。", reasonFreeAreaInvalid:"有效開口率無效，因此無法計算出口速度。", reasonWidthUnavailable:"未提供出風口寬度，因此無法計算出口速度。", reasonWidthInvalid:"出風口寬度無效，因此無法計算出口速度。", reasonHeightUnavailable:"未提供出風口高度，因此無法計算出口速度。", reasonHeightInvalid:"出風口高度無效，因此無法計算出口速度。", reasonUnknown:"出口速度不可用，請查看技術原因代碼。",
};

const dictionaries: Record<Language,Record<TranslationKey,string>> = {"zh-TW":zh,en};
type I18nValue = {language:Language;setLanguage:(language:Language)=>void;t:(key:TranslationKey,values?:Record<string,string|number>)=>string};
const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({children}:{children:ReactNode}) {
  const [language,setLanguageState] = useState<Language>(() => localStorage.getItem("add.language") === "en" ? "en" : "zh-TW");
  const value = useMemo<I18nValue>(() => ({language,setLanguage:(next) => {localStorage.setItem("add.language",next);setLanguageState(next);},t:(key,values) => {let text=dictionaries[language][key];Object.entries(values ?? {}).forEach(([name,value])=>{text=text.replace(`{${name}}`,String(value));});return text;}}),[language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(){const value=useContext(I18nContext);if(!value)throw new Error("I18nProvider is required");return value;}
export function unavailableReason(code:string|null,t:I18nValue["t"]){const keys:Record<string,TranslationKey>={OUTLET_VELOCITY_FREE_AREA_RATIO_UNAVAILABLE:"reasonFreeAreaUnavailable",OUTLET_VELOCITY_FREE_AREA_RATIO_INVALID:"reasonFreeAreaInvalid",OUTLET_VELOCITY_WIDTH_MM_UNAVAILABLE:"reasonWidthUnavailable",OUTLET_VELOCITY_WIDTH_MM_INVALID:"reasonWidthInvalid",OUTLET_VELOCITY_HEIGHT_MM_UNAVAILABLE:"reasonHeightUnavailable",OUTLET_VELOCITY_HEIGHT_MM_INVALID:"reasonHeightInvalid"};return t(keys[code ?? ""] ?? "reasonUnknown");}
